### PR TITLE
fix: dc.close() is async

### LINKED ISSUE #80: dc.close() should take a callback

### LINKED ISSUE #321: Improve the way we destroy a dc context
At the moment we rely on v8 to garbage collect objects from core. This works roughly as follows:

* a call to `napi_create_external()` is made to wrap a c pointer, which is returned back to javascript
* in the call to `napi_create_external()` a pointer to a function is passed, which gets called when v8 garbage collects the corresponding javascript object
* the c function then cleans up the underlying dc object, e.g. by calling `dc_context_unref()`, `dc_chat_unref()`, `dc_contact_unref()` etc

This works, but if _any_ of these `dc_xyz_unref()` takes a lot of time, it means the v8 thread will hang, which in turn causes the desktop application to hang until this is done.

It seems to me that this only happens for `dc_context_unref()`, which I assume is doing much more under the hood.

In any case, there are two approaches here:

1. try to figure out why `dc_context_unref()` takes a lot of time, fix that and pretend it's raining
1. make e.g. `dc.close()` async, and call `dc_context_unref()` explicitly, i.e. this function should _not_ be called by the v8 thread during garbage collection

The second option is probably the most correct and more future proof way of doing it. Obviously we can also combine this with the first option.

Related: https://github.com/deltachat/deltachat-node/issues/80 and https://github.com/deltachat/deltachat-node/pull/308#discussion_r285103580

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes #80 
Closes #321 

This should prevent desktop from hanging in the ui thread during garbage collection.

Note that the integration tests will still hang until the threads have been stopped in `dc-rs`. There's no way around this unless we do a `setTimeout()` and `process.exit(0)`.

### CODE REVIEW

File: src/module.c [hunk 1]
```diff
@@ -71,7 +71,13 @@ static uintptr_t dc_event_handler(dc_context_t* dc_context, int event, uintptr_t
   }
 
   // Start tracing events here. DC_EVENT_GET_STRING is just too spammy.
-  TRACE("event %d", event);
+#ifdef DEBUG
+  if (event == DC_EVENT_INFO) {
+    TRACE("event INFO %s", (char*)data2);
```
Comment (ralphtheninja) [inline src/module.c]: We get some INFO events when closing the context and might want to print them out during DEBUG.

File: src/module.c [hunk 2]
```diff
@@ -269,27 +275,6 @@ static void finalize_contact(napi_env env, void* data, void* hint) {
...
-    dcn_context->strtable = NULL;
-
-    pthread_cond_destroy(&dcn_context->dc_event_http_cond);
-    pthread_mutex_destroy(&dcn_context->dc_event_http_mutex);
-
-    TRACE("done");
-
-    free(dcn_context);
-  }
-}
```
Comment (ralphtheninja) [inline src/module.c]: This means we no longer clean up the context using v8 garbage collection. This is all moved to `dcn_close()`.

File: src/module.c [hunk 3]
```diff
@@ -504,12 +488,133 @@ NAPI_METHOD(dcn_clear_string_table) {
...
+
+static void dcn_close_execute(napi_env env, void* data) {
+  dcn_close_carrier_t* carrier = (dcn_close_carrier_t*)data;
+
+  TRACE("enter");
+  dcn_context_t* dcn_context = carrier->dcn_context;
+
+  if (dcn_context->threadsafe_event_handler) {
+    TRACE("event handler registered, releasing one reference");
+    napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
```
Comment (ralphtheninja) [inline src/module.c]: This comes from `dcn_unset_event_handler()`.

File: src/module.c [hunk 4]
```diff
@@ -504,12 +488,133 @@ NAPI_METHOD(dcn_clear_string_table) {
...
+      uv_thread_join(&dcn_context->mvbox_thread);
+      TRACE("< joining sentbox_thread..");
+      uv_thread_join(&dcn_context->sentbox_thread);
+
+      TRACE("ALL threads joined");
+
+      dcn_context->imap_thread = 0;
+      dcn_context->smtp_thread = 0;
+      dcn_context->mvbox_thread = 0;
+      dcn_context->sentbox_thread = 0;
```
Comment (ralphtheninja) [inline src/module.c]: This comes from `dcn_stop_threads()`.

File: src/module.c [hunk 5]
```diff
@@ -504,12 +488,133 @@ NAPI_METHOD(dcn_clear_string_table) {
...
+  dcn_context->strtable = NULL;
+
+  TRACE("cleaning up http_cond");
+  pthread_cond_destroy(&dcn_context->dc_event_http_cond);
+
+  TRACE("cleaning up http_mutex");
+  pthread_mutex_destroy(&dcn_context->dc_event_http_mutex);
+
+  TRACE("freeing dcn_context");
+  free(dcn_context);
```
Comment (ralphtheninja) [inline src/module.c]: This comes from `finalize_context()`.

**Comment by ralphtheninja** [comment]
@nicodh Maybe you could try out this branch? Note that you can do `./node_modules/.bin/node-gyp rebuild --debug` to get full debug output from the c-layer. This will help with more information if there's something else not working.

**Comment by nicodh** [comment]
@ralphtheninja unfortunately no debug output on hanging. I see a lot of module.c debug output when selecting a chat, typing a draft, but as soon as I click on "Send message" everything is frozen and not a single line added to debug log... 
:-(

**Comment by nicodh** [comment]
Actually - now I see some more log debug statements:
> module.c:76 dc_event_handler() event INFO IMAP-IDLE has data.
> module.c:76 dc_event_handler() event INFO INBOX-IDLE ended.
> module.c:76 dc_event_handler() event INFO INBOX-jobs started...
> module.c:76 dc_event_handler() event INFO INBOX-jobs ended.
> module.c:76 dc_event_handler() event INFO INBOX-fetch started...
> module.c:76 dc_event_handler() event INFO 0 mails read from "INBOX".
> module.c:76 dc_event_handler() event INFO INBOX-fetch done in 26 ms.
> module.c:76 dc_event_handler() event INFO INBOX-IDLE started...
> module.c:76 dc_event_handler() event INFO IMAP-IDLE has data.
> module.c:76 dc_event_handler() event INFO MVBOX-IDLE ended.
etc.
which means Electron is frozen, but dc core is still running...

**Comment by ralphtheninja** [comment]
@nicodh Ok, so there's some additional problems when sending messages. Maybe you can trace down from electron into node bindings where it hangs. I can't reproduce unfortunately.

@dignifiedquire Can you send messages or does electron hang for you as well?

**Comment by Jikstra** [comment]
> Note that the integration tests will still hang until the threads have been stopped in `dc-rs`. There's no way around this unless we do a `setTimeout()` and `process.exit(0)`.

Does dc-rs stop the threads? Or do the integration tests still hang forever?

**Comment by ralphtheninja** [comment]
> Does dc-rs stop the threads? Or do the integration tests still hang forever?

They don't hang forever.

**Comment by Jikstra** [comment]
> They don't hang forever.

Wow that was fast :D

**Comment by ralphtheninja** [comment]
> Wow that was fast :D

That's all I do with my life. Hang in front of this PR :D

**Comment by ralphtheninja** [comment]
@nicodh How are you starting desktop? `npm run dev`?
